# Generated by Django 4.2.1 on 2023-05-31 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count_of_uses_user', models.IntegerField(default=None, verbose_name='Количество использований от одного пользователя')),
                ('count_of_uses', models.IntegerField(default=None, verbose_name='Количество использований')),
                ('name', models.CharField(default=None, max_length=12, verbose_name='Название промокода')),
                ('deadline', models.DateField(default=None, verbose_name='Срок действия')),
                ('users', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
