version: '3.8'
services:
    backend:
        tty: true 
        build: backend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - ./backend:/root/server
        depends_on:
            - redis
    # frontend:
    #     build: frontend
    #     command: npm run serve
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         - ./frontend:/app
    #         - /app/node_modules
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes: 
            - cache:/data
    mailhog:
        image: mailhog/mailhog
        ports:
            - '8025:8025'
        logging:
            driver: json-file
    celery:
        restart: always
        build:
            context: ./backend
        command: celery -A core.celery worker --beat --loglevel=info
        volumes:
            - ./backend:/app
        depends_on:
            - backend
            - redis
volumes:
  cache:
    driver: local