version: '3.8'
services:
    backend:
        tty: true 
        build: backend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
    frontend:
        build: frontend
        command: npm run serve
        ports:
            - 8080:8080