# Generated by Django 4.2.1 on 2023-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
