# Generated by Django 4.2.1 on 2023-06-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('method', models.CharField(max_length=10)),
                ('user_agent', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'VisitLog',
                'verbose_name_plural': 'VisitLogs',
            },
        ),
    ]
