# Generated by Django 4.2.1 on 2023-06-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='method',
            field=models.CharField(max_length=10, verbose_name='Метод'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='user_agent',
            field=models.CharField(max_length=200, verbose_name='Пользователь'),
        ),
    ]
