# Generated by Django 4.2.1 on 2023-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена')),
                ('material', models.CharField(default='Silver', max_length=32, verbose_name='Материал')),
                ('img_path', models.CharField(default='/default-img.png', max_length=9999, verbose_name='Путь к изображению')),
                ('color', models.CharField(default='Серый', max_length=32, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Good',
                'verbose_name_plural': 'Goods',
            },
        ),
    ]
