# Generated by Django 4.2.1 on 2023-05-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='img_path',
        ),
        migrations.AddField(
            model_name='good',
            name='img',
            field=models.ImageField(default=None, max_length=9999, null=True, upload_to='', verbose_name='Изоюражение'),
        ),
    ]
