# Generated by Django 4.2.1 on 2023-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='good',
            name='alloy',
        ),
        migrations.AddField(
            model_name='good',
            name='color',
            field=models.CharField(default='Серый', max_length=32, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='good',
            name='img_path',
            field=models.CharField(default='/default-img.png', max_length=9999, verbose_name='Путь к изображению'),
        ),
        migrations.AddField(
            model_name='good',
            name='material',
            field=models.CharField(default='Silver', max_length=32, verbose_name='Материал'),
        ),
    ]
