# Generated by Django 4.2.1 on 2023-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_good_img_path_good_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='brand',
            field=models.CharField(default=None, max_length=32, verbose_name='Брэнд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='img',
            field=models.ImageField(default=None, max_length=9999, null=True, upload_to='static/img/', verbose_name='Изоюражение'),
        ),
    ]
