# Generated by Django 4.2.1 on 2023-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good_brand_alter_good_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='img',
            field=models.CharField(default=None, max_length=9999, null=True, verbose_name='Изоюражение'),
        ),
    ]
